Update MixedModels.md
cran-task-views/MixedModels pull request #42
Opened 2023-01-19 16:00 UTC by mattfidler

This adds the commercial options from `babelmixr2`

2023-01-19 17:10 UTC, palday commented on MixedModels.md
> +- Other software: [NONMEM](https://www.iconplc.com/innovation/nonmem/)  for ODE based mixed models (commerical).
```suggestion
- Other software: [NONMEM](https://www.iconplc.com/innovation/nonmem/) for ODE based mixed models (commercial).
```

2023-01-19 17:10 UTC, palday approved these changes

2023-01-20 00:14 UTC, bbolker requested changes
My markup is clunky here, sorry. [] are insertions, [DELETE ...] and [CHANGE ...] should speak for themselves. These are suggestions (except for the fixed typo) rather than mandatory requirements.

allows `r pkg("nlmixr2")` models to [be] translated and run in either the commercial tool 
  [Monolix](https://monolix.lixoft.com/) or [NONMEM](https://www.iconplc.com/innovation/nonmem/) and then read[s] the results 
  back in to create a standardized `nlmixr2` fit object. This fit object runs the diagnostics in `nlmixr2` and [DELETE the] compares [them]
  to the ones output in the commercial software to "validate" the fit object [CHANGE represents the → against the] output of the commercial tool.  
  It also interfaces with free tools [CHANGE as well like → such as] `r pkg("PKNCA)` [CHANGE for automatically using observed Pharmcokinetic → in order to use observed pharmacokinetic] (PK) data 
  [CHANGE for → to derive]  initial estimates of PK models.

2023-01-20 00:15 UTC, bbolker commented
PS thanks for the contribution!

2023-01-21 00:32 UTC, mattfidler commented
> PS thanks for the contribution! (I forget: is there a PK task view either in existence or in prep??)

There is a PK task view; https://cran.r-project.org/web/views/Pharmacokinetics.html

2023-01-21 00:33 UTC, mattfidler commented
I hope I got everything you suggested.  Thanks for the edit!

2023-01-21 00:47 UTC, bbolker commented
didn't fix typo in "Pharmcokinetic" (which I also wouldn't capitalize).  (Sorry, I would fix this myself, but not 100% clear on how to make edits on PRs ...)

2023-01-21 01:41 UTC, mattfidler commented
Great catch

2023-01-21 01:52 UTC, merged